In [1]:
import pandas as pd

Book = pd.read_csv(r"C:\Users\SHIVA KUMAR\Desktop\Assigmnt\Recommendations\Book_recommendation.csv")

In [2]:
Book

,Index,User_ID,Book_Title,Book_Rating
0,1,276726,Classical Mythology,5
1,2,276729,Clara Callan,3
2,3,276729,Decision in Normandy,6
3,4,276736,Flu: The Story of the Great Influenza Pandemic...,8
4,5,276737,The Mummies of Urumchi,6
...,...,...,...,...
9995,9996,162121,American Fried: Adventures of a Happy Eater.,7
9996,9997,162121,Cannibal In Manhattan,9
9997,9998,162121,How to Flirt: A Practical Guide,7
9998,9999,162121,Twilight,8
9999,10000,162129,Kids Say the Darndest Things,6

In [3]:
Book["Book_Title"].value_counts()

Fahrenheit 451                                              5
Charlie and the Chocolate Factory                           4
The Subtle Knife (His Dark Materials, Book 2)               4
Vanished                                                    4
Ender's Game (Ender Wiggins Saga (Paperback))               4
                                                           ..
Murder on St. Mark's Place (Gaslight Mysteries)             1
State of Grace                                              1
Valsalva's Maneuver: Mots Justes and Indispensable Terms    1
I love you, I hate you                                      1
Kids Say the Darndest Things                                1
Name: Book_Title, Length: 9659, dtype: int64

In [4]:
Book.sort_values('User_ID')
Book.shape

(10000, 4)

In [5]:
Book[Book.duplicated()].shape

(0, 4)

In [6]:
Book.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Index        10000 non-null  int64
 1   User_ID      10000 non-null  int64
 2   Book_Title   10000 non-null  object
 3   Book_Rating  10000 non-null  int64
dtypes: int64(3), object(1)
memory usage: 312.6+ KB

In [7]:
#no of unique users in the dataset
len(Book["User_ID"].unique())

2182

In [8]:
Book['Book_Rating'].value_counts()

8     2283
7     2076
10    1732
9     1493
5     1007
6      920
4      237
3      146
2       63
1       43
Name: Book_Rating, dtype: int64

In [9]:
Book.head()

,Index,User_ID,Book_Title,Book_Rating
0,1,276726,Classical Mythology,5
1,2,276729,Clara Callan,3
2,3,276729,Decision in Normandy,6
3,4,276736,Flu: The Story of the Great Influenza Pandemic...,8
4,5,276737,The Mummies of Urumchi,6

In [10]:
Book.head()

,Index,User_ID,Book_Title,Book_Rating
0,1,276726,Classical Mythology,5
1,2,276729,Clara Callan,3
2,3,276729,Decision in Normandy,6
3,4,276736,Flu: The Story of the Great Influenza Pandemic...,8
4,5,276737,The Mummies of Urumchi,6

In [11]:
Book = Book.groupby(['User_ID', 'Book_Title'])['Book_Rating'].mean().reset_index()

In [12]:
User = Book.pivot(index= 'User_ID', columns= 'Book_Title', values= 'Book_Rating')

In [13]:
User.head(60)

Book_Title,"Jason, Madison &amp",Other Stories;Merril;1985;McClelland &amp,Repairing PC Drives &amp,'48,'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR,01-01-00: A Novel of the Millennium,"1,401 More Things That P*Ss Me Off",10 Commandments Of Dating,"100 Great Fantasy Short, Short Stories",...,Zora Hurston and the Chinaberry Tree (Reading Rainbow Book),\Even Monkeys Fall from Trees\ and Other Japanese Proverbs,\I Won't Learn from You\: And Other Thoughts on Creative Maladjustment,"\More More More,\ Said the Baby",\O\ Is for Outlaw,"\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character","\Well, there's your problem\: Cartoons",iI Paradiso Degli Orchi,stardust,Ãƒ?Ã‚?bermorgen.
User_ID,,,,,,,,,,,,,,,,,,,,,
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN
185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#impute those NANs with '0' values

User.fillna(0, inplace=True)

In [15]:
User

Book_Title,"Jason, Madison &amp",Other Stories;Merril;1985;McClelland &amp,Repairing PC Drives &amp,'48,'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR,01-01-00: A Novel of the Millennium,"1,401 More Things That P*Ss Me Off",10 Commandments Of Dating,"100 Great Fantasy Short, Short Stories",...,Zora Hurston and the Chinaberry Tree (Reading Rainbow Book),\Even Monkeys Fall from Trees\ and Other Japanese Proverbs,\I Won't Learn from You\: And Other Thoughts on Creative Maladjustment,"\More More More,\ Said the Baby",\O\ Is for Outlaw,"\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character","\Well, there's your problem\: Cartoons",iI Paradiso Degli Orchi,stardust,Ãƒ?Ã‚?bermorgen.
User_ID,,,,,,,,,,,,,,,,,,,,,
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278846,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278851,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0
278852,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278854,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
#finding similer kind of Users by metrics of algorithm is pairwise_distances
# and calculating Cosine 

from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

In [17]:
User_1 = 1 - pairwise_distances(User.values,metric= 'cosine')

In [18]:
User_1

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [19]:
#Store the results in a dataFrame

user_users = pd.DataFrame(User_1)

In [20]:
user_users

,0,1,2,3,4,5,6,7,8,9,...,2172,2173,2174,2175,2176,2177,2178,2179,2180,2181
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2177,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2178,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2179,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2180,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2181,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [21]:
Book.User_ID.unique()

array([     8,      9,     10, ..., 278851, 278852, 278854], dtype=int64)

In [22]:
#set the index and column names to users

user_users.index = Book.User_ID.unique()
user_users.columns = Book.User_ID.unique()

In [23]:
user_users.iloc[0:15,0:15]

     8    9    10   12   14   16   17   19   22   26   32   39   42   44   51
8   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
10  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
12  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
14  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
16  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
17  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
19  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
22  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
26  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
32  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
39  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
42  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
44  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
51  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [24]:
#filling the 1 values which it called as daigonal
import numpy as np
np.fill_diagonal(User_1,0)

In [25]:
user_users.iloc[0:15,0:15]

     8    9    10   12   14   16   17   19   22   26   32   39   42   44   51
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
16  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
17  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
19  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
22  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
26  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
32  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
39  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
42  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
44  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
51  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [26]:
# these are the most similer Users 
user_users.idxmax(axis=1)[0:50]   #it is matching similarties by columns wise

#user number 8 is similer to user 8
#user number 10,12,14 etc similer to 8
#user number 51 is similar to 3757

8           8
9           8
10          8
12          8
14          8
16          8
17          8
19     278418
22          8
26          8
32          8
39          8
42          8
44          8
51       3757
53       1996
56          8
64          8
67          8
69          8
70          8
73          8
75          8
78          8
81          8
82        882
83     276861
85       1211
86     276780
87          8
88          8
91          8
92          8
97          8
99          8
102         8
107         8
109         8
110         8
114         8
125         8
129         8
133         8
137         8
141         8
160       899
162         8
165         8
169         8
176         8
dtype: int64

In [30]:
#evaluating the user to user what they are in intersted  
PS = Book[(Book['User_ID'] == 1211) | (Book['User_ID'] == 899)]
PS

      User_ID                                         Book_Title  Book_Rating
1062      899  Era bom que trocÃƒÂ¡ssemos umas ideias sobre o a...          9.0
1063      899    Running from Safety: An Adventure of the Spirit          2.0
1064      899                    Tales of a Fourth Grade Nothing          8.0
1065      899  The Morning River : A Novel of the Great Misso...          7.0
1066      899  The Pre-Raphaelite Vision (Phaidon Miniature E...          4.0
1372     1211   A Circle of Silver (Circle of Silver Chronicles)          9.0
1373     1211                       Amours sorciÃƒ?Ã‚Â¨res (export)          5.0
1374     1211                        Another Roadside Attraction          9.0
1375     1211                                       BLACK THRONE          8.0
1376     1211                                  Becoming a Writer          9.0
1377     1211                                        Black House          8.5
1378     1211                                Book of D'ni (Myst)          6.0
1379     1211                                          Christine          9.0
1380     1211                                     Coyote V. Acme          6.0
1381     1211                                             Cradle          9.0
1382     1211                                      Damia (Rowan)          9.0
1383     1211                                     Falling Angels          8.0
1384     1211                                     Fear of Flying          8.0
1385     1211                           French Lessons: A Memoir          6.0
1386     1211                                Generation Warriors          9.0
1387     1211  Guns, Germs, and Steel: The Fates of Human Soc...          7.0
1388     1211                   Hearts In Atlantis : New Fiction          7.0
1389     1211                          Holidays on Ice : Stories          7.0
1390     1211  Il bar sotto il mare (Universale economica Fel...          9.0
1391     1211                       Love Warps the Mind a Little          9.0
1392     1211        Masks (Star Trek The Next Generation, No 7)          8.0
1393     1211  Midnight Champagne : A Novel (Mysteries &amp; ...          8.0
1394     1211                               Millroy the Magician         10.0
1395     1211                             More Die of Heartbreak          9.0
1396     1211                                  Pebble in the Sky          7.0
1397     1211                               Pets' Letters to God          7.0
1398     1211  Pride and Prejudice (Everyman Paperback Classics)         10.0
1399     1211                                       Private Eyes          8.0
1400     1211  Required Reading: Why Our American Classics Ma...          9.0
1401     1211                              STONES FROM THE RIVER          7.0
1402     1211                                      Shipping News          9.0
1403     1211                                    Sisters in Arms          8.0
1404     1211                    Something Wicked This Way Comes          9.0
1405     1211               The Art and Craft of Feature Writing          2.0
1406     1211                               The Boys of My Youth          8.0
1407     1211                                 The Cat in the Hat          8.0
1408     1211                The Clan of the Cave Bear : a novel         10.0
1409     1211                                          The Dwarf          9.0
1410     1211                                          The Lover          8.0
1411     1211                                  The Pelican Brief          9.0
1412     1211       The Princess and the Pea (Loveswept, No 589)          8.0
1413     1211  The Quotable Traveler: Wise Words for Traveler...          8.0
1414     1211                               The Valley of Horses          9.0
1415     1211      The White Dragon (Dragonriders of Pern, V. 3)          9.0
1416     1211  The Women of Brewster Place (Penguin Contempor...          7.0
1417     1211             Three Musketeers (Wordsworth Classics)          9.0
1418     1211                                Vivir Para Contarla          8.0
1419     1211                                      Wall of Brass          8.0
1420     1211                   Wheels Of Fire (Serrated Edge 2)          7.0
1421     1211  Who's Running Your Career?: Creating Stable Wo...          8.0
1422     1211       Wicca: A Guide for the Solitary Practitioner          8.0
1423     1211  Witta: An Irish Pagan Tradition (Llewellyn's W...          9.0

In [29]:
# Assuming df is your DataFrame and user_users.idxmax(axis=1) contains similar user IDs

similar_user_ids = user_users.idxmax(axis=1)[0:50]  # Adjust the range as needed

# Filter the original DataFrame to get records of similar users
similar_user_records = Book[Book['User_ID'].isin(similar_user_ids)]

# Print or inspect the records
sp = pd.DataFrame(similar_user_records)
sp.head(20)

      User_ID                                         Book_Title  Book_Rating
0           8                            Ancient Celtic Romances          5.0
1           8                Keepers of the Earth Teachers Guide          6.0
2           8                                  The Art Of Celtia          7.0
3           8                            The Celts Activity Book          6.0
4           8  The Western way: A practical guide to the West...          5.0
5           8                                           Truckers          5.0
6           8                                              Wings          5.0
1012      882         AixÃƒÂ² ÃƒÂ©s RÃƒÂ dio Pica (ColÃ‚Â¨lecciÃƒÂ³ Embat)         10.0
1013      882  Babinski Reflex: And 70 Other Useful and Amazi...         10.0
1014      882  CCNA Exam Notes: Cisco Certified Network Assoc...          9.0
1015      882  CCNA: Cisco Certified Network Associate Study ...         10.0
1016      882                                       Cat's Cradle          8.0
1017      882  Chicken Soup for the Teenage Soul II (Chicken ...         10.0
1018      882                                            Contact          8.0
1019      882   Devil's Waltz (Alex Delaware Novels (Paperback))          9.0
1020      882                  Dinner at the Homesick Restaurant          9.0
1021      882            Dress Your Family in Corduroy and Denim          9.0
1022      882  Drinking Coffee Elsewhere (Today Show Book Clu...          7.0
1023      882  Elvis, Jesus &amp; Coca-Cola (Kinky Friedman N...         10.0
1024      882                                      Hornet's Nest         10.0

In [31]:
#storing the users in one class to send recommendations which 
#to recommend the book to a another user who already read the book might get intersted to read

first_user = Book[Book['User_ID']==8]
first_user

   User_ID                                         Book_Title  Book_Rating
0        8                            Ancient Celtic Romances          5.0
1        8                Keepers of the Earth Teachers Guide          6.0
2        8                                  The Art Of Celtia          7.0
3        8                            The Celts Activity Book          6.0
4        8  The Western way: A practical guide to the West...          5.0
5        8                                           Truckers          5.0
6        8                                              Wings          5.0

In [32]:
first_user.Book_Title

0                              Ancient Celtic Romances
1                  Keepers of the Earth Teachers Guide
2                                    The Art Of Celtia
3                              The Celts Activity Book
4    The Western way: A practical guide to the West...
5                                             Truckers
6                                                Wings
Name: Book_Title, dtype: object

In [33]:
second_user = Book[Book['User_ID']== 882]
second_user

      User_ID                                         Book_Title  Book_Rating
1012      882         AixÃƒÂ² ÃƒÂ©s RÃƒÂ dio Pica (ColÃ‚Â¨lecciÃƒÂ³ Embat)         10.0
1013      882  Babinski Reflex: And 70 Other Useful and Amazi...         10.0
1014      882  CCNA Exam Notes: Cisco Certified Network Assoc...          9.0
1015      882  CCNA: Cisco Certified Network Associate Study ...         10.0
1016      882                                       Cat's Cradle          8.0
1017      882  Chicken Soup for the Teenage Soul II (Chicken ...         10.0
1018      882                                            Contact          8.0
1019      882   Devil's Waltz (Alex Delaware Novels (Paperback))          9.0
1020      882                  Dinner at the Homesick Restaurant          9.0
1021      882            Dress Your Family in Corduroy and Denim          9.0
1022      882  Drinking Coffee Elsewhere (Today Show Book Clu...          7.0
1023      882  Elvis, Jesus &amp; Coca-Cola (Kinky Friedman N...         10.0
1024      882                                      Hornet's Nest         10.0
1025      882                             I love you, I hate you         10.0
1026      882                                           I, Robot          5.0
1027      882                I, Robot:The Illustrated Screenplay          9.0
1028      882                                      Jurassic Park          5.0
1029      882                                     La casa pierde         10.0
1030      882                                      Leon Africano         10.0
1031      882                                Lore of the Unicorn          5.0
1032      882    Murder on St. Mark's Place (Gaslight Mysteries)         10.0
1033      882                                         Rabbit Run          5.0
1034      882                           Ransom (Steel, Danielle)          9.0
1035      882                                 Resistencia humana         10.0
1036      882  Soul Survivors: A New Beginning for Adults Abu...          4.0
1037      882                                     State of Grace         10.0
1038      882                         Still Life with Woodpecker         10.0
1039      882                                             Summer         10.0
1040      882          The 27-Ingredient Chili Con Carne Murders         10.0
1041      882      The Clinic (Alex Delaware Novels (Paperback))          5.0
1042      882      The Dragon Reborn (The Wheel of Time, Book 3)          6.0
1043      882  The Ethical Slut: A Guide to Infinite Sexual P...          7.0
1044      882                                       The Fourth K         10.0
1045      882                                   The Husband Test         10.0
1046      882                 The Invisible Man (Bantam Classic)          9.0
1047      882                                    The Root Cellar         10.0
1048      882                              The Ship Who Searched         10.0
1049      882                            The Tao of Love and Sex          9.0
1050      882                          The Temple of My Familiar         10.0
1051      882  The Western Guide to Feng Shui: Creating Balan...          6.0
1052      882  Valsalva's Maneuver: Mots Justes and Indispens...         10.0
1053      882                                    Way Things Work          9.0

In [34]:

book_read_by_user1 = list(set(first_user.Book_Title))
book_read_by_user2 = list(set(second_user.Book_Title))

for Book_name in book_read_by_user1:
    if Book_name not in book_read_by_user2:
        print("Recomendation to a second_user :", Book_name)

Recomendation to a second_user : Wings
Recomendation to a second_user : The Western way: A practical guide to the Western mystery tradition
Recomendation to a second_user : Truckers
Recomendation to a second_user : Ancient Celtic Romances
Recomendation to a second_user : The Celts Activity Book
Recomendation to a second_user : The Art Of Celtia
Recomendation to a second_user : Keepers of the Earth Teachers Guide